In [1]:
import pandas as pd
import numpy as np


In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

код numpy

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 25.1 ms


чистый код python

In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 203 ms
Wall time: 905 ms


In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[-0.98284862,  0.46628569, -0.08175773],
       [ 1.12279051, -0.88075182, -0.82206107]])

In [9]:
data * 10

array([[-9.82848619,  4.66285694, -0.81757726],
       [11.22790509, -8.80751815, -8.22061069]])

In [10]:
data + data

array([[-1.96569724,  0.93257139, -0.16351545],
       [ 2.24558102, -1.76150363, -1.64412214]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6, 7.5, 8, 0, 1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2, 3, 2))

array([[[1.16474705e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [4.45060182e-308, 1.58817677e-052]],

       [[4.97647320e-091, 1.42023784e+161],
        [8.46381617e+164, 5.99137016e-038],
        [3.99910963e+252, 1.90979636e-312]]])

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])