In [1]:
a = 10
b = 10
c = a * b
print(c)

100


In [2]:
import pandas as pd
import numpy as np


In [5]:
my_arr = np.arange(1000000)

In [6]:
my_list = list(range(1000000))

код numpy

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.2 ms, sys: 14.1 ms, total: 29.3 ms
Wall time: 33.4 ms


чистый код python

In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 681 ms, sys: 303 ms, total: 985 ms
Wall time: 986 ms


In [9]:
data = np.random.randn(2,3)

In [10]:
data

array([[-0.46343835, -1.65590863,  0.11244309],
       [ 1.65132737, -0.66761905, -0.91212085]])

In [11]:
data * 10

array([[ -4.63438353, -16.5590863 ,   1.12443093],
       [ 16.51327366,  -6.67619053,  -9.12120853]])

In [12]:
data + data

array([[-0.92687671, -3.31181726,  0.22488619],
       [ 3.30265473, -1.33523811, -1.82424171]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [16]:
data1 = [6, 7.5, 8, 0, 1]

In [17]:
arr1 = np.array(data1)

In [18]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [20]:
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int64')

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.empty((2, 3, 2))

array([[[4.85733125e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])